# Generated by roxytest: do not edit by hand!

# File R/utils.R: @testexamples

test_that("Function envvar_defined() @ L38", {
  
  envvar_defined("HOME")
  expect_error(envvar_defined("FOOBAR"))
  expect_true(envvar_defined("HOME"))
})

