# Generated by roxytest: do not edit by hand!

# File R/meta_oncoanalyser_wgts_existing_both.R: @testexamples

test_that("Function meta_oncoanalyser_wgts_existing_both() @ L15", {
  
  pmeta <- "extdata/portaldb_workflow_top4.rds" |>
    system.file(package = "rportal") |>
    readr::read_rds()
  (m <- meta_oncoanalyser_wgts_existing_both(pmeta))
  expect_equal(all(c("s3_outdir_oncoanalyser", "LibraryID_tumor_wts", "gds_bam_tumor_wgs") %in% colnames(m)), TRUE)
})

