# Generated by roxytest: do not edit by hand!

# File R/meta_rnasum.R: @testexamples

test_that("Function meta_rnasum() @ L14", {
  
  pmeta <- system.file("extdata/portal_meta_top4.csv", package = "rportal")
  (m <- meta_rnasum(pmeta))
  expect_equal(m$rnasum_dataset[1], "PANCAN")
  expect_equal(basename(m$gds_outfile_rnasum_html[4]), "MDX230467.RNAseq_report.html")
})

