# Generated by roxytest: do not edit by hand!

# File R/meta_wgs_alignment_qc.R: @testexamples

test_that("Function meta_wgs_alignment_qc() @ L13", {
  
  pmeta <- system.file("extdata/portal_meta_top4.csv", package = "rportal")
  (m <- meta_wgs_alignment_qc(pmeta))
  expect_equal("Lane" %in% colnames(m), TRUE)
})

