# Generated by roxytest: do not edit by hand!

# File R/meta_star_alignment.R: @testexamples

test_that("Function meta_star_alignment() @ L13", {
  
  pmeta <- system.file("extdata/portal_meta_top4.csv", package = "rportal")
  (m <- meta_star_alignment(pmeta))
  expect_equal(all(c("s3_outdir_star", "LibraryID") %in% colnames(m)), TRUE)
})

