# Generated by roxytest: do not edit by hand!

# File R/meta_bcl_convert.R: @testexamples

test_that("Function meta_bcl_convert() @ L14", {
  
  pmeta <- system.file("extdata/portal_meta_top4.csv", package = "rportal")
  (m <- meta_bcl_convert(pmeta))
  expect_equal(sum(!is.na(m$topup_or_rerun)), 1)
  expect_equal(length(unique(m$portal_run_id)), 4)
})

