# Generated by roxytest: do not edit by hand!

# File R/meta_wts_tumor_only.R: @testexamples

test_that("Function meta_wts_tumor_only() @ L14", {
  
  pmeta <- system.file("extdata/portal_meta_top4.csv", package = "rportal")
  (m <- meta_wts_tumor_only(pmeta))
  expect_equal(length(unique(m$portal_run_id)), 4)
  expect_equal(length(unique(m$LibraryID)), 4)
})

