# Generated by roxytest: do not edit by hand!

# File R/meta_oncoanalyser_wgs.R: @testexamples

test_that("Function meta_oncoanalyser_wgs() @ L13", {
  
  pmeta <- system.file("extdata/portal_meta_top4.csv", package = "rportal")
  (m <- meta_oncoanalyser_wgs(pmeta))
  expect_equal(all(c("s3_outdir_oncoanalyser", "LibraryID_tumor", "gds_bam_tumor") %in% colnames(m)), TRUE)
})

