# Generated by roxytest: do not edit by hand!

# File R/meta_icav1.R: @testexamples

test_that("Function meta_bcl_convert() @ L21", {
  
  pmeta <- "extdata/portaldb_workflow_top4.rds" |>
    system.file(package = "rportal") |>
    readr::read_rds()
  (m <- meta_bcl_convert(pmeta))
  
  expect_equal(sum(!is.na(m$topup_or_rerun)), 0)
  expect_equal(length(unique(m$portal_run_id)), 4)
})


test_that("Function meta_oncoanalyser_wgs() @ L100", {
  
  pmeta <- "extdata/portaldb_workflow_top4.rds" |>
    system.file(package = "rportal") |>
    readr::read_rds()
  (m <- meta_oncoanalyser_wgs(pmeta))
  expect_equal(all(c("s3_outdir_oncoanalyser", "LibraryID_tumor", "gds_bam_tumor") %in% colnames(m)), TRUE)
})


test_that("Function meta_oncoanalyser_wgts_existing_both() @ L158", {
  
  pmeta <- "extdata/portaldb_workflow_top4.rds" |>
    system.file(package = "rportal") |>
    readr::read_rds()
  (m <- meta_oncoanalyser_wgts_existing_both(pmeta))
  expect_equal(all(c("s3_outdir_oncoanalyser", "LibraryID_tumor_wts", "gds_bam_tumor_wgs") %in% colnames(m)), TRUE)
})


test_that("Function meta_oncoanalyser_wts() @ L226", {
  
  pmeta <- "extdata/portaldb_workflow_top4.rds" |>
    system.file(package = "rportal") |>
    readr::read_rds()
  (m <- meta_oncoanalyser_wts(pmeta))
  expect_equal(all(c("s3_outdir_oncoanalyser", "LibraryID", "s3_bam") %in% colnames(m)), TRUE)
})


test_that("Function meta_rnasum() @ L280", {
  
  pmeta <- "extdata/portaldb_workflow_top4.rds" |>
    system.file(package = "rportal") |>
    readr::read_rds()
  (m <- meta_rnasum(pmeta))
  expect_equal(m$rnasum_dataset[1], "PANCAN")
  expect_equal(basename(m$gds_outfile_rnasum_html[4]), "PRJ222637.RNAseq_report.html")
})


test_that("Function meta_sash() @ L365", {
  
  pmeta <- "extdata/portaldb_workflow_top4.rds" |>
    system.file(package = "rportal") |>
    readr::read_rds()
  (m <- meta_sash(pmeta))
  expect_equal(all(c("s3_indir_oncoanalyser", "LibraryID_tumor", "s3_outdir_sash") %in% colnames(m)), TRUE)
})


test_that("Function meta_star_alignment() @ L425", {
  
  pmeta <- "extdata/portaldb_workflow_top4.rds" |>
    system.file(package = "rportal") |>
    readr::read_rds()
  (m <- meta_star_alignment(pmeta))
  expect_equal(all(c("s3_outdir_star", "LibraryID") %in% colnames(m)), TRUE)
})


test_that("Function meta_tso_ctdna_tumor_only() @ L479", {
  
  pmeta <- "extdata/portaldb_workflow_top4.rds" |>
    system.file(package = "rportal") |>
    readr::read_rds()
  (m <- meta_tso_ctdna_tumor_only(pmeta))
  expect_equal(length(unique(m$portal_run_id)), 4)
})


test_that("Function meta_umccrise() @ L533", {
  
  pmeta <- "extdata/portaldb_workflow_top4.rds" |>
    system.file(package = "rportal") |>
    readr::read_rds()
  (m <- meta_umccrise(pmeta))
  expect_equal(all(c("LibraryID_normal", "LibraryID_tumor") %in% colnames(m)), TRUE)
})


test_that("Function meta_wgs_alignment_qc() @ L633", {
  
  pmeta <- "extdata/portaldb_workflow_top4.rds" |>
    system.file(package = "rportal") |>
    readr::read_rds()
  (m <- meta_wgs_alignment_qc(pmeta))
  expect_equal("lane" %in% colnames(m), TRUE)
})


test_that("Function meta_wgs_tumor_normal() @ L701", {
  
  pmeta <- "extdata/portaldb_workflow_top4.rds" |>
    system.file(package = "rportal") |>
    readr::read_rds()
  (m <- meta_wgs_tumor_normal(pmeta))
  expect_equal("SubjectID" %in% colnames(m), TRUE)
})


test_that("Function meta_wts_alignment_qc() @ L796", {
  
  pmeta <- "extdata/portaldb_workflow_top4.rds" |>
    system.file(package = "rportal") |>
    readr::read_rds()
  (m <- meta_wts_alignment_qc(pmeta))
  expect_equal("lane" %in% colnames(m), TRUE)
})


test_that("Function meta_wts_tumor_only() @ L865", {
  
  pmeta <- "extdata/portaldb_workflow_top4.rds" |>
    system.file(package = "rportal") |>
    readr::read_rds()
  (m <- meta_wts_tumor_only(pmeta))
  expect_equal(length(unique(m$portal_run_id)), 4)
  expect_equal(length(unique(m$LibraryID)), 4)
})

