# Generated by roxytest: do not edit by hand!

# File R/meta_wgs_tumor_normal.R: @testexamples

test_that("Function meta_wgs_tumor_normal() @ L15", {
  
  pmeta <- "extdata/portaldb_workflow_top4.rds" |>
    system.file(package = "rportal") |>
    readr::read_rds()
  (m <- meta_wgs_tumor_normal(pmeta))
  expect_equal("SubjectID" %in% colnames(m), TRUE)
})

