# Generated by roxytest: do not edit by hand!

# File R/meta_tso_ctdna_tumor_only.R: @testexamples

test_that("Function meta_tso_ctdna_tumor_only() @ L13", {
  
  pmeta <- system.file("extdata/portal_meta_top4.csv", package = "rportal")
  (m <- meta_tso_ctdna_tumor_only(pmeta))
  expect_equal(length(unique(m$portal_run_id)), 2)
})

