# Generated by roxytest: do not edit by hand!

# File R/meta_umccrise.R: @testexamples

test_that("Function meta_umccrise() @ L13", {
  
  pmeta <- system.file("extdata/portal_meta_top4.csv", package = "rportal")
  (m <- meta_umccrise(pmeta))
  expect_equal(all(c("LibraryID_normal", "LibraryID_tumor") %in% colnames(m)), TRUE)
})

