# Generated by roxytest: do not edit by hand!

# File R/meta_sash.R: @testexamples

test_that("Function meta_sash() @ L13", {
  
  pmeta <- system.file("extdata/portal_meta_top4.csv", package = "rportal")
  (m <- meta_sash(pmeta))
  expect_equal(all(c("s3_indir_oncoanalyser", "LibraryID_tumor", "s3_outdir_sash") %in% colnames(m)), TRUE)
})

