# Generated by roxytest: do not edit by hand!

# File R/meta_wgs_tumor_normal.R: @testexamples

test_that("Function meta_wgs_tumor_normal() @ L13", {
  
  pmeta <- system.file("extdata/portal_meta_top4.csv", package = "rportal")
  (m <- meta_wgs_tumor_normal(pmeta))
  expect_equal("SubjectID" %in% colnames(m), TRUE)
})

