# Generated by roxytest: do not edit by hand!

# File R/meta_oncoanalyser_wts.R: @testexamples

test_that("Function meta_oncoanalyser_wts() @ L13", {
  
  pmeta <- system.file("extdata/portal_meta_top4.csv", package = "rportal")
  (m <- meta_oncoanalyser_wts(pmeta))
  expect_equal(all(c("s3_outdir_oncoanalyser", "LibraryID", "s3_bam") %in% colnames(m)), TRUE)
})

